// Generated by SugarLisp v0.5.8
require("./require");

var readline = require("readline"),
  logo = require("../lib/logo-ogre"),
  transpiler = require("../lib/transpiler"),
  packageJson = require('../package.json'),
  prefix = "sugar> ";

exports.runrepl = function() {
  var rl = readline.createInterface(process.stdin, process.stdout);
  rl.on('line', function(line) {
    (function() {
      try {
        var l = transpiler.transpile(line, "stdin.ls", {
          for: "server"
        });
        console.log(this.eval(l));

      } catch (e) {
        return (function(err) {
          console.log(err);
        })(e);
      }
    })();
    rl.setPrompt(prefix, prefix.length);
    return rl.prompt();
  });
  rl.on('close', function() {
    console.log("Bye!");
    return process.exit(0);
  });
  console.log(logo());
  console.log(['                              ', 'SugarLisp v', packageJson.version, '\n'].join(''));
  rl.setPrompt(prefix, prefix.length);
  return rl.prompt();
};