// Generated by SugarLisp v0.6.5
require("./require");

var engine = require("./engine"),
  readline = require("readline"),
  repldialect = require("./repl-dialect"),
  logo = require("../lib/logo-ogre"),
  packageJson = require('../package.json');

exports.runrepl = function(ext) {
  ext = (ext || "sugar");
  var prompt = [ext, "> "].join('');
  var sugarlisp = new engine.Engine(undefined, ["stdin.", ext].join(''));
  sugarlisp.use_dialect(repldialect);

  var rl = readline.createInterface(process.stdin, process.stdout);
  rl.on('line', function(line) {
    (function() {
      try {
        var ec = this;
        var result = sugarlisp.eval(line, {
          for: "server",
          jsevalcontext: ec
        });
        console.log(result);

      } catch (e) {
        return (function(err) {
          console.log(err);
        })(e);
      }
    })();
    rl.setPrompt(prompt, prompt.length);
    return rl.prompt();
  });
  rl.on('close', function() {
    console.log("Bye!");
    return process.exit(0);
  });
  console.log(logo());
  console.log(['                              ', 'SugarLisp v', packageJson.version, '\n'].join(''));
  rl.setPrompt(prompt, prompt.length);
  return rl.prompt();
};