// Generated by SugarLisp v0.6.5
var fs = require("fs"),
  path = require("path"),
  transpiler = require("../lib/transpiler");

function requireable(ext) {
  return require.extensions[ext] = function(module, filename) {
    var code = fs.readFileSync(filename, "utf8");
    return module._compile(transpiler.transpile(code, path.relative(process.cwd(), filename)), filename);
  };
}

[
  ".score",
  ".ls",
  ".slisp",
  ".sugar",
  ".slon",
  ".slml",
  ".slss",
  ".sson",
  ".ssml",
  ".ssss"
].forEach(function(ext) {
  return requireable(ext);
});